### ISSUE TITLE
player with 8 letters near end of game

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#48] opened 2022-06-30 07:04 UTC
From a game I wasn't a part of, in the version just before you fixed the red dot issue, near the end of the game, a player showed 8 letters in their hand:

![image001](https://user-images.githubusercontent.com/20344426/176611645-fc93fe53-4c14-45dc-bc76-b4672489df98.png)

This happened right after a two-letter word was played, but only one was received back from the letter bag even though there were two remaining.  After refreshing, the number of tiles in each players' hand disappeared.  Everyone else's view showed all players had 7 tiles initially, but after refresh, their views no longer showed the number of tiles either.

![image002](https://user-images.githubusercontent.com/20344426/176611682-f7d2eb33-db46-4944-8a3b-c0a2b4c9400c.png)

There are no exceptions or anything in the log file.  Thanks.

**Comment by cdot** [comment] 2022-06-30 07:47
Thanks Paul - unfortunately the images above have the rack cropped out, which is unfortunately key to debugging this :-(

Could you possibly attach the relevant .game file? That would help enormously.

**Comment by pkolano** [comment] 2022-06-30 21:41
Believe this is the one.  I changed the name to .log so github would allow me to upload.  Thanks.

[e23dad22ee4234b8.log](https://github.com/cdot/Xanado/files/9023577/e23dad22ee4234b8.log)

**Comment by cdot** [comment] 2022-07-01 06:14
Thank you - I'm putting together a simulator to allow replay of a game for detailed analysis.

**Comment by cdot** [comment] 2022-07-25 14:06
I can't reproduce this. The game provided runs through the simulator perfectly. SO it's a UI issue, that can't be nailed down until we have the steps needed to reproduce it. So leaving this as "Help wanted" in the hope that some more detail is forthcoming (or it has been fixed)

**Comment by cdot** [comment] 2022-09-19 07:19
I'm going to close this for now, as the codebase has changed a lot since it was reported. Please re-reference this issue in any future report of the same issue.

**Closed by cdot** 2022-09-19 07:19 UTC
Labels: question
